name: Master Template

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  #Schedule can use a cron expression to trigger a workflow at a specific time of day
  #Only runs on the main branch
  #Runs only once per every 5 minutes
  release:
    types: [published, created]
  schedule:
    #Runs at 5:30 only on Monday and Wednesday
    #- cron: '30 5 * * 1,3'
    #Runs at 05:30, on day 1 of the month, and on Tuesday and Thursday.
    #- cron: '30 5 1 * 2,4'
    - cron: '*/3 * * * *'

jobs:
  My_Cool_Job_Name: 
      #Specifying the wrong target here will cause the job to wait for a runner indefinately
      #runs-on: ubuntu-latets
      runs-on: ubuntu-latest
      steps:
        - name: Do Work Son
          run: echo "The current server time is $(date)"
        - uses: actions/checkout@v2
        
